import type { DocumentFormatConfig, RuntimeBrandingConfig } from './ConfigSchemas';

export const builtInDefaultFormat: DocumentFormatConfig = {
  FormatId: 'TaxInvoice',
  FormatName: 'GST Invoice',
  Description: 'Built-in default GST invoice format for clean installations.',
  Fields: [
    {
      FieldId: 'InvoiceDate',
      Label: 'Invoice Date',
      Type: 'Date',
      Required: true,
      SampleValue: '2026-06-04',
    },
    {
      FieldId: 'CustomerName',
      Label: 'Customer Name',
      Type: 'Text',
      Required: true,
      Placeholder: 'Enter customer name',
      SampleValue: 'Sample Customer',
    },
    {
      FieldId: 'CustomerGstin',
      Label: 'Customer GSTIN',
      Type: 'Text',
      Required: false,
      SampleValue: '',
    },
    {
      FieldId: 'BillingAddress',
      Label: 'Billing Address',
      Type: 'Textarea',
      Required: false,
      SampleValue: 'Sample Traders, Main Road',
    },
    {
      FieldId: 'GrandTotal',
      Label: 'Grand Total',
      Type: 'Money',
      ReadOnly: true,
      SampleValue: '1180.00',
    },
  ],
  LineItemSections: [
    {
      SectionId: 'Items',
      Label: 'Items',
      MinRows: 1,
      MaxRows: 500,
      EssentialColumns: ['ItemName', 'Quantity', 'Rate', 'Amount'],
      AllowAddRows: true,
      AllowDuplicateRows: true,
      AllowReorderRows: true,
      AllowBulkPaste: true,
      AllowBulkUpload: true,
      Fields: [
        {
          FieldId: 'ItemName',
          Label: 'Item Name',
          Type: 'Text',
          Required: true,
          SampleValue: 'Sample Item',
        },
        {
          FieldId: 'Quantity',
          Label: 'Quantity',
          Type: 'Quantity',
          Required: true,
          DefaultValue: '1.000',
          Precision: 3,
          SampleValue: '2.000',
        },
        {
          FieldId: 'Rate',
          Label: 'Rate',
          Type: 'Rate',
          Required: true,
          Precision: 4,
          SampleValue: '500.0000',
        },
        {
          FieldId: 'Amount',
          Label: 'Amount',
          Type: 'Money',
          ReadOnly: true,
          Calculated: true,
          CalculationOrder: 10,
          Formula: 'Quantity * Rate',
          SampleValue: '1000.00',
        },
      ],
    },
  ],
  CalculationPolicy: {
    Currency: 'INR',
    MoneyPrecision: 2,
    QuantityPrecision: 3,
    RatePrecision: 4,
    RoundingMode: 'HALF_UP',
    TaxRoundingLevel: 'Line',
    DateFormat: 'DD-MM-YYYY',
    DateTimeFormat: 'DD-MM-YYYY HH:mm',
    DefaultPrefix: '',
    DefaultSuffix: '',
  },
};

export const defaultRuntimeBrandingSetting: RuntimeBrandingConfig = {
  ApplicationName: 'VaultBill',
  CompanyName: '',
  Tagline: 'Configure once. Bill, print, and report anywhere.',
  ApplicationLogoAssetId: '',
  PrintLogoAssetId: '',
  FaviconAssetId: '',
};
