/** @format */

import type { AppRecord } from './RecordStoreSchema';

/** Demo records shown in the browser-only workspace and seeded desktop sample. */
export const demoSeedRecords: readonly AppRecord[] = [
    {
        recordId: 'demo-finalized-1',
        formatId: 'TaxInvoice',
        formatName: 'GST Invoice',
        documentNumber: 'GST-000001',
        status: 'Finalized',
        invoiceDate: '2026-06-01',
        customerName: 'Aster Works',
        gstin: '29ABCDE1234F1Z5',
        state: 'Karnataka',
        billingAddress: '12 Market Road, Bengaluru',
        lineItems: [
            {
                rowId: 'demo-row-1',
                itemName: 'Consulting services',
                hsnSac: '9983',
                quantity: '1',
                rate: '12500.00',
                taxPercent: '18',
                amount: '14750.00',
                values: {},
            },
        ],
        grandTotal: '14750.00',
        fieldValues: {},
        createdAt: '2026-06-01T10:00:00.000Z',
        updatedAt: '2026-06-01T10:00:00.000Z',
        createdBy: 'demo_user',
        createdByName: 'Demo User',
    },
    {
        recordId: 'demo-finalized-2',
        formatId: 'TaxInvoice',
        formatName: 'GST Invoice',
        documentNumber: 'GST-000002',
        status: 'Finalized',
        invoiceDate: '2026-06-03',
        customerName: 'Nila Foods',
        gstin: '33AAACN1234A1Z2',
        state: 'Tamil Nadu',
        billingAddress: '8 Lake View Street, Chennai',
        lineItems: [
            {
                rowId: 'demo-row-2',
                itemName: 'Packaging design',
                hsnSac: '9983',
                quantity: '1',
                rate: '7500.00',
                taxPercent: '18',
                amount: '8850.00',
                values: {},
            },
        ],
        grandTotal: '8850.00',
        fieldValues: {},
        createdAt: '2026-06-03T08:30:00.000Z',
        updatedAt: '2026-06-03T08:30:00.000Z',
        createdBy: 'demo_user',
        createdByName: 'Demo User',
    },
    {
        recordId: 'demo-cancelled-1',
        formatId: 'TaxInvoice',
        formatName: 'GST Invoice',
        documentNumber: 'GST-000003',
        status: 'Cancelled',
        invoiceDate: '2026-06-04',
        customerName: 'Aster Works',
        gstin: '29ABCDE1234F1Z5',
        state: 'Karnataka',
        billingAddress: '12 Market Road, Bengaluru',
        lineItems: [
            {
                rowId: 'demo-row-3',
                itemName: 'Duplicate service entry',
                hsnSac: '9983',
                quantity: '1',
                rate: '2000.00',
                taxPercent: '18',
                amount: '2360.00',
                values: {},
            },
        ],
        grandTotal: '2360.00',
        fieldValues: {},
        createdAt: '2026-06-04T09:00:00.000Z',
        updatedAt: '2026-06-04T11:00:00.000Z',
        createdBy: 'demo_user',
        createdByName: 'Demo User',
        cancellationReason: 'Duplicate invoice',
    },
    {
        recordId: 'demo-draft-1',
        formatId: 'TaxInvoice',
        formatName: 'GST Invoice',
        documentNumber: null,
        status: 'Draft',
        invoiceDate: '2026-06-06',
        customerName: 'Harbor Retail',
        gstin: '',
        state: 'Kerala',
        billingAddress: '21 Port Lane, Kochi',
        lineItems: [
            {
                rowId: 'demo-row-4',
                itemName: 'Store signage',
                hsnSac: '9983',
                quantity: '1',
                rate: '5000.00',
                taxPercent: '18',
                amount: '5900.00',
                values: {},
            },
        ],
        grandTotal: '5900.00',
        fieldValues: {},
        createdAt: '2026-06-06T07:15:00.000Z',
        updatedAt: '2026-06-06T07:15:00.000Z',
        createdBy: 'demo_user',
        createdByName: 'Demo User',
    },
    {
        recordId: 'demo-finalized-4',
        formatId: 'TaxInvoice',
        formatName: 'GST Invoice',
        documentNumber: 'GST-000004',
        status: 'Finalized',
        invoiceDate: '2026-06-07',
        customerName: 'Meridian Labs',
        gstin: '27AACCM9876B1Z1',
        state: 'Maharashtra',
        billingAddress: '44 Innovation Park, Pune',
        lineItems: [
            {
                rowId: 'demo-row-5',
                itemName: 'Annual support',
                hsnSac: '9983',
                quantity: '1',
                rate: '18000.00',
                taxPercent: '18',
                amount: '21240.00',
                values: {},
            },
        ],
        grandTotal: '21240.00',
        fieldValues: {},
        createdAt: '2026-06-07T06:45:00.000Z',
        updatedAt: '2026-06-07T06:45:00.000Z',
        createdBy: 'demo_user',
        createdByName: 'Demo User',
    },
];
